// Predefined messages used for responses in the application
const message = {
  // General messages
  generateUrl: 'url generated successfully',
  contactUsEmail: 'You have received a contact email',
  serverError: 'Something went wrong. Please try again later!',
  deleteContent: 'Content has been deleted',
  deleteAllContents: 'Removed all contents',
  notFound: 'Requested content not found',
  inactiveUser: 'User not active',
  incorrectPassword: 'Incorrect password',
  incorrectDetails: 'incorrect details',
  emailDoesNotExist: "Email doesn't exist",
  invalidOtp: 'Invalid OTP',
  loggedIn: 'login successful',
  tokenGenerate: 'access token generated successfully',
  authSuccess: 'Authentication successful',
  otpVerified: 'OTP verified successfully',
  otpAlreadyVerified: 'Email has already verified',
  otpSent: 'OTP has been sent',
  newsletterSubscription: 'Successfully subscribed to newsletter',
  unauthorized: 'You are not authorized to perform this operation',
  alreadySubscribed: 'You already have an active subscription',
  assessmentsAdded: 'Added assessments.',
  normalRegistration: 'You have already registered using email and password',
  loggedOut: 'Logged out successfully',
  basePathNotFound: 'Base path not found',
  signedUrlError: 'Unable to retrieve file information',
  invalidCurriculum: 'Curriculum details not found',
  responseSaved: 'Response saved successfully',
  alreadyResponded: 'You have already responded to this',
  noActiveSubscription: 'You are not yet subscribed to the platform',
  mentorApproved: 'Mentor registration approved',
  mentorRejected: 'Mentor registration rejected',
  accountRejected: 'You account has been rejected',
  awaitingBackgroundCheck: 'Background checking is in progress',
  verified: 'Verified successfully',
  invalidToken: 'Invalid token passed',
  emailMissing: 'Invalid payload. Email is required.',
  emailAvailable: 'Email address available for registration',
  calendarSaved: 'Calendar details saved successfully',
  dataFetched: 'Data fetched successfully',
  sessionNotFound: 'Community Session Not Found',
  sessionDeleted: 'Community Session deleted Successfully',
  accessBlocked: 'Your access has been blocked',
  noEmail: 'No email address is associated with this account',
  mentorAssigned: 'You have assigned to a mentor',
  contentUpdated: 'Contents updated',
  saved: 'Saved successfully',
  curriculumUpdated: 'Curriculum updated successfully',
  onboard: 'Successfully onboard',
  // User-related messages
  user: {
    userExistsInAnotherRole: 'User already exists with another role',
    userCreated: 'User details created',
    userNameExists: 'Username already exists',
    userEmailExists: 'Useremail already exists',
    userNotFound: 'User details not found',
    userNotVerified: 'User is not verified by email',
    userNotCreated: 'user is not created successfully',
  },
  // Other specific messages
  clientNotFound: 'Client not found',
  noMentors: 'No active mentors',
  scheduleRejection: "Meeting can't be scheduled. Another meeting pending",
  invalidOption: 'Invalid option',
  invalidPayload: 'Invalid payload',
  memberProfileUpdate: 'Member profile updated',
  meetingNotFound: 'Meeting Not Found',
  meetingCancel: 'Meeting canceled',
  mentorNotAssigned: 'Mentor is not assigned',
  alreadyCanceled: 'You have already canceled the subscription',
  subscriptionCancel: 'You have successfully canceled subscription',
  passwordNotMatch: 'Passwords are not matching',
  passwordUpdated: 'Password updated successfully',
  promptAdded: 'Prompt added successfully',
  getPrompt: 'Prompt retrieved successfully',
  currentPasswordSuccess: 'Successfully matched with current password',
  currentPasswordError: 'You entered an invalid password',
  titleNotExist: 'Title not exist',
  groupCreationFailed: 'Failed to create group',
  internalServerError: 'Internal server error',
};
export default message;
